### ISSUE TITLE
Responsive images on home page skip 640 size

### ISSUE THREAD

**Issue by gpbmike** [tannerdolby/eleventy-photo-gallery#18]
On https://eleventy-gallery.netlify.app/, if you resize the width of the browser and watch the network tab, you can see that the 640 size images never load.

I don't know enough about `<picture>` and `<source>` to debug, but it looks like you want a 640 size to load in there at some point.

```html
<source type="image/webp" srcset="/images/terrace-window-320.webp 320w, /images/terrace-window-480.webp 480w, /images/terrace-window-640.webp 640w, /images/terrace-window-1024.webp 1024w" sizes="(max-width: 480px) 33.3vw, (max-width: 640px) 50vw, 100vw">
```

https://github.com/tannerdolby/eleventy-photo-gallery/blob/7993fc6eeccb667dd09bb7b878dacd30ffcd6c71/src/_includes/layouts/base.njk#L46-L56

![image](https://user-images.githubusercontent.com/8754/126584050-babe5623-b018-43c1-9821-831998b3e15e.png)

As a side note, it looks like the widest those home pages images get is 354px.

**Comment by tannerdolby** [comment]
> I don't know enough about <picture> and <source> to debug, but it looks like you want a 640 size to load in there at some point.

There already exists a 640w descriptor image in the `srcset`. The problem was (actually partly my own fault), I declared an explicit `height` on the images in this grid which was unnecessary (and might have caused problems with srcset/sizes). With responsive images, we only constrain the width (ie width constrained) and let the height do its thing. When we define an explicit `height` like `height: 18rem` then the responsive images kinda are throwing srcset/sizes out the window and sticking the the largest available source to handle that 18rem (288px) height of the content box, as if the media conditions/lengths in `sizes` aren't even there.

This is 3 column grid with each image occupying 33.3vw of the page width. I don't wan't to load a 640w unless the browser determines that slot is "ideal" and more crisp (better resolution) than the next larger image in the srcset which is 1024w. If I load a 320w source then it's going to be super blurry unless the browser determines the viewport "must" use that source as its the "best" fit for the slot. Responsive images are quite a bit to get a handle on, but hopefully the discussion in this issue helps to get you started in the direction.

>  The `sizes` attribute tells the browser how many pixels it needs by describing the final rendered width of our image. Think of sizes as a way to give the browser a bit of information about the page’s layout a little ahead of time, so that it can pick a source before it has parsed or rendered any of the page’s CSS.

With current `srcset` and `sizes` we are telling the browser its available image resources and allowing it to decide which image source is best suited for the "slot" at a specific viewport. Before changing sizes, if the viewport is less than 480px use 33.3vw (ie 33.3% of the largest 1024px image since its a 3 column grid) otherwise if the viewport is greater than 480px but less than 640px serve the 50vw image, otherwise if viewport > 640px serve the 100vw (100% of the viewport width which would choose the 1024px image). 

The trick with `<picture>` and `srcset` is really the `sizes` attribute, as were explicitly telling the browser how/when to render an image and which image src from `srcset` to decide on using for that "slot". My `sizes` needed to be updated and now the 320w is shown then 640w then 1024w. The browser will load what "best fits" the available slot based on the provided `srcset` and `sizes` attributes.

> As a side note, it looks like the widest those home pages images get is 354px.

Almost, the rendered size is 397px by 298px at viewports > 1200px.

<img width="517" alt="Screen Shot 2021-07-21 at 10 27 07 PM" src="https://user-images.githubusercontent.com/48612525/126593557-a26c2389-ef3e-47db-be27-d94371bf5ba4.png">

Resources on responsive image markup:
- https://www.smashingmagazine.com/2014/05/responsive-images-done-right-guide-picture-srcset/ (Highly recommend)
- https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by tannerdolby** [comment]
Thank you for taking the time to point this out @gpbmike !

After I updated the `sizes` attribute to: 

```css
sizes="(min-width: 600px) 50vw, (min-width: 800px) 100vw, 33.3vw",
```

each of the images in `srcset` are loaded accordingly and can be confirmed in the network tab, as well as by hovering your mouse over the nested `<img>` and see its "Current source". Below is few demo videos as GitHub limits video files to 10MB per embed. I did notice, I had to do a fresh `npm run dev` and open a new tab (or reload cache) before inspecting the page with DevTools and seeing the "Current source" change correctly along with the network tab. Not sure if this is a Chrome nuance but nonetheless, the following widths are used and verified in Network:

- 320px
- 480px
- 640px
- 1024px

https://user-images.githubusercontent.com/48612525/126610511-bba7becb-3054-48eb-aa28-4f3fcc8f70cb.mov

_Current source: 1024px_
<img width="1280" alt="Screen Shot 2021-07-22 at 1 13 47 AM" src="https://user-images.githubusercontent.com/48612525/126610533-f7e24704-c213-4d48-9d95-b5c56348ef55.png">

_Current source: 640px_
<img width="1280" alt="Screen Shot 2021-07-22 at 1 13 28 AM" src="https://user-images.githubusercontent.com/48612525/126610576-0e591004-970f-40a4-9d41-352e8d06cfae.png">

_Current source: 480px_
<img width="1279" alt="Screen Shot 2021-07-22 at 1 12 59 AM" src="https://user-images.githubusercontent.com/48612525/126610590-eb64f883-d428-457e-9d65-59d4c6960a55.png">

_Current source: 320px_
<img width="1279" alt="Screen Shot 2021-07-22 at 1 12 22 AM" src="https://user-images.githubusercontent.com/48612525/126610612-590ffc0e-3f33-4dbc-a5db-efb5369e8778.png">

**Comment by tannerdolby** [comment]
I reckon this is ready to close now. Feel free to provide another repro in a separate issue if you encounter any bugs/inconsistencies in the future and I'm happy to take a look. Thanks again for pointing this out!
